main: com.alyxferrari.servercensor.ServerCensor
name: ServerCensor
version: 1.4
author: Alyx Ferrari
description: Custom slur-censoring plugin written by admin Alyx
commands:
   pronouns:
      description: Sets your pronouns.
      usage: /pronouns <type pronouns here>
      permission: customalyx.pronouns
   report:
      description: Report bad behavior.
      usage: /report <username> <reason>
      permission: customalyx.report
   spawn:
      description: Alias for /warp spawn
      usage: /spawn
      permission: customalyx.spawn
   is:
      description: Island command
      usage: /is
      permission: customalyx.skyblock
      aliases: [island, skyblock, sb]
   isnearest:
      description: Teleport nearest player to island
      usage: /isnearest
      permission: customalyx.isnearest