main: com.alyxferrari.servercensor.TransMemesCustom
name: trinityplugin
version: 1.6
author: Alyx Ferrari
description: Custom plugin written by admin Alyx
api-version: 1.16
commands:
   pronouns:
      description: Sets your pronouns.
      usage: /pronouns <type pronouns here>
      permission: customalyx.pronouns
   report:
      description: Report bad behavior.
      usage: /report <username> <reason>
      permission: customalyx.report
   spawn:
      description: Alias for /warp spawn
      usage: /spawn
      permission: customalyx.spawn
   is:
      description: Island command
      usage: /is
      permission: customalyx.skyblock
      aliases: [island, skyblock, sb]
   isnearest:
      description: Teleport nearest player to island
      usage: /isnearest
      permission: customalyx.isnearest
   sell:
      description: Forces /sell:sell
      usage: /sell
      permission: customalyx.sell
   elytra:
      description: Get moderator elytra
      usage: /elytra <name>
      permission: customalyx.elytra
   bow:
      description: Get bow
      usage: /bow
      permission: customalyx.bow
   crossbow:
      description: Get crossbow
      usage: /crossbow
      permission: customalyx.crossbow
   score:
      description: Get PvP KDR
      usage: /score
      permission: customalyx.score
   trail:
      description: Set particle trail
      usage: /trail
      permission: customalyx.trail
      aliases: [trails]
   tone:
      description: Summarised list of tone indicators
      usage: /tone
      permission: customalyx.tone