main: com.alyxferrari.servercensor.ServerCensor
name: ServerCensor
version: 1.0
author: Alyx Ferrari
description: Custom slur-censoring plugin written by admin Alyx
commands:
   pronouns:
      description: Sets your pronouns.
      usage: /pronouns <type pronouns here>
      permission: customalyx.pronouns
      permission-message: